### PR TITLE
Continue if repo contributors are empty

### LINKED ISSUE #42: Organization stats fail if any repo is empty
When checking an organization, any empty repo will cause the action to fail. Simply bad timing could mean a user creates a repo as the action is running.

Actual:
Exits with
```
Expected status_code 200 but got 204
Error getting contributors for repository: foo/bar
No more repositories will be processed. Please delete the (empty?) repository and try again.
204 [No message]
```
Expected;
Continues, perhaps logging
```
Error getting contributors for repository: foo/bar. It may be empty.
```

### PR DESCRIPTION
**Pull request by zkoppert**
Fixes #42

## Proposed Changes

- Continue if a repo's contributors are empty instead of panic

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
- [x] run `make lint` and fix any issues that you have introduced
- [x] run `make test` and ensure you have test coverage for the lines you are introducing

### Reviewer
- [x] Label as either `bug`, `documentation`, `enhancement`, `infrastructure`, or `breaking`

### CODE REVIEW

**Comment by zkoppert** [comment]
@mister-ben Hopefully this works for what you are thinking.

**Comment by mister-ben** [comment]
Thanks, that works. Although I think the message to delete the repo and try again if you need the repo is at best confusing, and potentially dangerously misleading in case it's ever triggered by an unforeseen reason other than being an empty repo.

**Comment by zkoppert** [comment]
@mister-ben I updated to just remove that confusing line. I'm thinking that the notification that we couldn't get collaborators from the repo and the status code should be helpful without being misleading.

**Comment by zkoppert** [comment]
Creating a release to get this out there. Thanks!!

**Pull request merged**
